name: Laravel automated tests

on:
  push:
    branches: ['master', 'feature/**']
  pull_request:
    branches: ['master']

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - php: 8.3
                      illuminate: ^11.0
                    - php: 8.2
                      illuminate: ^11.0
                    - php: 8.2
                      illuminate: ^10.0
                    - php: 8.1
                      illuminate: ^10.0
                    - php: 8.1
                      illuminate: ^9.0
                    - php: 8.1
                      illuminate: ^8.0
                    - php: 8.0
                      illuminate: ^8.0
                    - php: 7.4
                      illuminate: ^7.0

        name: PHP ${{ matrix.php }} - Illuminate ${{ matrix.illuminate }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Update composer
              run: composer self-update --2

            - name: Install dependencies
              run: composer require "illuminate/support:${{ matrix.illuminate }}" --no-interaction --no-progress --no-suggest

            - name: Execute tests
              run: composer test
